version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: annamart/react-app
    ports:
      - "3000:3000"
    volumes:
      - /usr/app/node_modules
      - ./:/usr/app
    container_name: react-web-app
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: annamart/react-app-test
    volumes:
      - /usr/app/node_modules
      - ./:/usr/app
    container_name: react-web-app-tests
    command: ["npm", "run", "test"]

